### ISSUE TITLE
krom won't start on linux

### ISSUE THREAD

**Issue by memilian** [Kode/Krom#10]
When trying to run a new project with Krom I get this error :
```Error: Couldn't wait on 127.0.0.1:7000```
If I try to run it a second time, I get the following after a few seconds :
```json
Haxe compilation server stopped.
******** Unhandled error in debug adapter - Unhandled promise rejection: 
{
  "id": 2010,
  "format": "Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).",
  "variables": {
    "_error": "Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9224",
    "_timeout": "10000"
  }
}
```

**Comment by RobDangerous** [comment]
It works for me on Linux so I'll need a few more details here: Kode Studio version, Kha revision (unless you use the bundled Kha), Linux distribution

**Comment by memilian** [comment]
I use Kode Studio 16.11.1, latest kha from git, but the same happens with the bundled version and the distribution is Manjaro (that's based on archlinux).
Is there any logfile somewhere ? I searched but couldn't find any

**Comment by memilian** [comment]
I should have checked that before submitting this issue but it seems I have a system service called "afs3-fileserver" listening on port 7000... I'll search what it is and if i can disable it

**Comment by RobDangerous** [comment]
The debug network connection has been overhauled completely, this is probably fixed (otherwise please reopen - to test current changes use vscode with the Kha extension pack, new Kode Studio will be out later this month).
