### ISSUE TITLE
Some issues with drawing primitives

### ISSUE THREAD

**Issue by trsh** [Kode/Krom#11]
HTML build, correct

![html](https://cloud.githubusercontent.com/assets/3727523/20861381/82ddb038-b997-11e6-90da-2c000438e696.png)

With Krom not a correct position and some 1px lines ar gone.

![krom](https://cloud.githubusercontent.com/assets/3727523/20861384/a2ab60fe-b997-11e6-8d33-c795a57b5aad.png)

Same code.

**Comment by RobDangerous** [comment]
What size is your window, is the content scaled?

**Comment by trsh** [comment]
1024, 800. Same as backbuffer. Nothing is scaled.

**Comment by RobDangerous** [comment]
Tested in Ubuntu 18.04 VM (your Krom window looks Ubuntuish) with latest Krom, seems to be fixed.
