### ISSUE TITLE
Krom doesnt expose Image::fromEncodedBytes

### ISSUE THREAD

**Issue by ianharrigan** [Kode/Krom#112]
https://github.com/haxeui/haxeui-kha/issues/22

**Comment by RobDangerous** [comment]
FAKE NEWS!!!1 It's in #111 and Kode/Kha#924

**Comment by ianharrigan** [comment]
Its not the right function name though.... the PR seems to show `createTextureFromEncodedBytes`

**Comment by RobDangerous** [comment]
Ha, see, there's no bugs in Kha.
