### ISSUE TITLE
cant build on Linux: error: no member named 'setTextureCompareMode' 

### ISSUE THREAD

**Issue by x17head** [Kode/Krom#117]
On Ubuntu 18.10 i believe i have all necessary libs 

`clang: warning: -lXi: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
../../Sources/main.cpp:1406:20: error: no member named 'setTextureCompareMode' in namespace 'Kore::Graphics4'
                Kore::Graphics4::setTextureCompareMode(*unit, enabled);
                ~~~~~~~~~~~~~~~~~^
../../Sources/main.cpp:1415:20: error: no member named 'setCubeMapCompareMode' in namespace 'Kore::Graphics4'
                Kore::Graphics4::setCubeMapCompareMode(*unit, enabled);
                ~~~~~~~~~~~~~~~~~^
`

**Comment by RobDangerous** [comment]
Fixed via 5d28c6bdf50c13713f17b62ab5c0a0508af2c129.
