### ISSUE TITLE
krom update

### ISSUE THREAD

**Issue by limbo127** [Kode/Krom#120]
Hello, 
from kode studio the message Krom uses API version 1 but Kha targets API version 2. Please update Krom.
but how update Krom
Regards
Nicolas Prochazka

**Comment by RobDangerous** [comment]
You can set the komPath option in Kode Studio to a self-compiled version of Krom, compilation instructions are included right here in the readme.
Alternatively you'll have to wait until I provide new binaries, hopefully somewhat soon.

**Comment by RobDangerous** [comment]
It's all updated now.
