### ISSUE TITLE
Gamepad right stick not working

### ISSUE THREAD

**Issue by tong** [Kode/Krom#126]
The right gamepad stick isn't working as expected using the krom target in armory.
The x-axis is actually y and the y-axis isn't providing any value.
Tested with PS3 and Xbox360 gamepads.

OS: Arch Linux 5.0.10
Krom version: https://github.com/armory3d/Krom/commit/725410134142951ae1f77d54c8afb1b52ac1ac77

**Comment by RobDangerous** [comment]
Linux gamepad support is provided by Kore, so please test with the latest Kore version and create an issue there if it doesn't work.
