### ISSUE TITLE
Not Drawing Fonts on Linux

### ISSUE THREAD

**Issue by jrdoughty** [Kode/Krom#13]
![fontsmissing](https://cloud.githubusercontent.com/assets/3956893/21211088/2661d23c-c246-11e6-93a0-3932de52369e.png)

To Replicate:
Download/Clone from https://github.com/jrdoughty/Kha-examples and Open Kode Studio in the GrowYourHoard folder. Compile to HTML5 and Krom to see the difference.

Machine Details:
Ubuntu 16.04 LTS
Kode Studio 16.11.1 (using bundled kha)
AMD FX 8350 Eight Core Processor
Radeon HD 7870
16GB Memory

**Comment by RobDangerous** [comment]
Fixed in latest Krom, tested in a Ubuntu 18.04 VM.
