### ISSUE TITLE
Sprites not showing up

### ISSUE THREAD

**Issue by jrdoughty** [Kode/Krom#14]
![fontsmissingmaingame](https://cloud.githubusercontent.com/assets/3956893/21211157/d2c7e2c8-c246-11e6-8bb1-66e18d6fd8d7.png)

To Replicate:
Download/Clone from https://github.com/jrdoughty/Kha-examples and Open Kode Studio in the GrowYourHoard folder. Compile to HTML5 and Krom, click top 'button' to see the difference.

Machine Details:
Ubuntu 16.04 LTS
Engine: Kha2d
Kode Studio 16.11.1 (using bundled kha)
AMD FX 8350 Eight Core Processor
Radeon HD 7870
16GB Memory

**Comment by RobDangerous** [comment]
Sprites are working in current Kha and Krom but haxe.Timer is not...

**Comment by RobDangerous** [comment]
And that's also fixed.

**Comment by jrdoughty** [comment]
That could explain why my projects have never worked in krom... I use those timers WAY too much...
