### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by 5Mixer** [Kode/Krom#140]
After pulling repository recursively and building per the README, clang fails with four errors. 

Log: https://gist.github.com/5Mixer/15b33e3e7874bf4459600427345832a9

Building a project with publicly published binaries gives the following GLSL error: https://gist.github.com/5Mixer/9f909965b4dc4ce32298847cbe4ac5bc 
In that case, the window opens however images appear incorrectly (in both texture and location).

When building the project with VS Code, compilation appears without apparent errors, however no window opens.

**Comment by RobDangerous** [comment]
Fixed.
