### ISSUE TITLE
Krom does not render more than one image at a time on Windows

### ISSUE THREAD

**Issue by smallfx** [Kode/Krom#141]
Hello! I am using the latest Kha and Krom on Windows 10.
I have tried pre-built binaries from the `Krom_bin` repo and building my own locally with exactly the same results as described below.

If I call `drawSubImage` with two different `Asset.image` arguments for each call, Kha only ever renders the first one.
The image asset files are .png format.

Here's some example code that I used to isolate the problem:
https://gist.github.com/smallfx/f45c1ae2ba47748f78841c9a4920f084

This seems like a very obvious issue, so I'm hesitant to think that it's an actual bug with Kha or Krom.
I'm using vscode with the kha extension pack and building for Krom via the green play button in the vscode debug menu.

Here is the result if I use two different images:
![Screenshot 2020-11-03 142817](https://user-images.githubusercontent.com/17196291/98047542-ee21bb80-1de0-11eb-98a2-a6307e54b18f.png)

Here is the result if I use two of the same image:
![Screenshot 2020-11-03 142848](https://user-images.githubusercontent.com/17196291/98047547-efeb7f00-1de0-11eb-819a-d46a5e760d2f.png)

*Of note:* if I call `drawRect` before the second image is drawn (location / size etc do not matter - it just needs to be called on the same context of course), it renders both of them perfectly fine.

**Comment by RobDangerous** [comment]
Fixed for Windows and Linux. macOS failed to compile for some reason.

**Comment by smallfx** [comment]
Tested and works! Will close this issue now, thanks for the speedy fix :)
