### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by e2002e** [Kode/Krom#151]
I'm trying to build Krom but first I can't use the configure script:
```
Node.js configure: Found Python 3.10.12...
gyp: Krom/krom_libs.gypi not found (cwd: Krom) while reading includes of Krom/node.gyp while trying to load Krom/node.gyp
Error running GY
```
(I removed my user name from cwd)

Trying to compile:
```

`Krom/Kinc/make:3
. `dirname "$0"`/Tools/platform.sh
^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
`

```
Using only Kink/make (without 'node')

`Using Kinc (82e7f461, M Sources/kinc/image.h, M Tools/linux_arm, M Tools/linux_arm64, M Tools/linux_x64, M Tools/macos, M Tools/windows_x64, M kfile.js) from /home/i20/Documents/armsdk/Krom/Kinc
kfile found.
Creating Linux project files.
Failed to include wayland-support, setting KINC_NO_WAYLAND.
Wayland error was: Failed to generate wayland protocol files forstable/viewporter/viewporter.xml
Compiling shader 1 of 2 (g1.frag).
Compiling shader 2 of 2 (g1.vert).
Error: Compiling shader g1.vert failed. Command was: Krom/Kinc/Tools/linux_x64/krafix spirv Krom/Kinc/GLSLShaders/g1.vert.glsl /g1.vert Krom/build linux`

**Comment by RobDangerous** [comment]
The main branch is in the middle of a switch back to V8 but other things became more important so work on that is currently stalled. Try compiling the chakra branch instead.
But please check if compiling a regular Kinc project like https://github.com/Kinc-Samples/Shader-Kinc works for you and report it on https://github.com/Kode/Kinc if it doesn't. That Kinc/make error message looks like your Linux installation is problematic and it would probably be beneficial to look into that.
