### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by e2002e** [Kode/Krom#152]
Hello, I'm trying to build Krom and get:

Using Kinc (b1954e8e) from /home/user/krom/Kinc
kfile found.
Creating Linux project files.
Failed to include wayland-support, setting KINC_NO_WAYLAND.
Wayland error was: Could not run wayland-scanner to ask for its version
Compiling shader 1 of 10 (g1.frag).
Compiling shader 2 of 10 (g1.vert).
Compiling shader 3 of 10 (painter-colored.frag).
Compiling shader 4 of 10 (painter-colored.vert).
Compiling shader 5 of 10 (painter-image.frag).
Compiling shader 6 of 10 (painter-image.vert).
Compiling shader 7 of 10 (painter-text.frag).
Compiling shader 8 of 10 (painter-text.vert).
Compiling shader 9 of 10 (painter-video.frag).
Compiling shader 10 of 10 (painter-video.vert).
Compiling...
clang++ -o "Krom"  -O2 compute.o openglunit.o g5ong4unit.o linuxunit.o posixunit.o rootunit.o a1unit.o audio.o graphics.o graphics_kore.o graphics_soft.o g4unit.o g5unit.o inputunit.o iounit.o stb_vorbis.o mathunit.o networkunit.o  -static-libgcc -static-libstdc++ -pthread -lasound -ldl -ludev -lGL -lEGL
/usr/bin/ld : linuxunit.o : dans la fonction « main » :
linuxunit.c:(.text+0x50c1) : référence indéfinie vers « kickstart »
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [makefile:8 : Krom] Erreur 1
Build time: 0m 0s
Compilation failed.
Error.

My OS is ubuntu 20 x64

**Comment by RobDangerous** [comment]
I already told you in #151 to compile the chakra branch instead.

**Comment by e2002e** [comment]
I got these errors with chakra:

Using Kinc (b1954e8e, M Backends/System/WindowsApp/Sources/kinc/backend/system.winrt.cpp) from /home/i20/Documents/armsdk/krom/Kinc
kfile found.
Creating Linux project files.
Failed to include wayland-support, setting KINC_NO_WAYLAND.
Wayland error was: Failed to generate wayland protocol files forstable/viewporter/viewporter.xml
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:1098:7)
    at node:kmake/Project:106:45
    at new Promise (<anonymous>)
    at loadProject (node:kmake/Project:73:12)
    at Project.addProject (node:kmake/Project:609:37)
    at eval (eval at <anonymous> (node:kmake/Project:108:27), <anonymous>:12:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Error: kfile did not call resolve, no project created.
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:1098:7)
    at node:kmake/Project:106:45
    at new Promise (<anonymous>)
    at loadProject (node:kmake/Project:73:12)
    at Project.addProject (node:kmake/Project:609:37)
    at eval (eval at <anonymous> (node:kmake/Project:108:27), <anonymous>:12:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by RobDangerous** [comment]
Wrong version of Kinc, make sure that git status doesn't show changes before you build.

**Comment by e2002e** [comment]
Ok i'll try. Bye.

**Comment by e2002e** [comment]
@RobDangerous I'd be gratefull if you could help me here, I need a modified version of Krom to run armory3d and need to compile it myself;

**Comment by RobDangerous** [comment]
For that you are at the wrong place. Krom was forked a long time ago for Armory and doesn't have all that much to do with the original Krom anymore as far as I know.
