### ISSUE TITLE
Does Krom worker in Browser?

### ISSUE THREAD

**Issue by hoseyjoe** [Kode/Krom#47]
Debugging in Kode it works great but when pointing browser to compiled file I receive 
`SystemImpl.hx:93 Uncaught ReferenceError: Krom is not defined
    at Function.kha_SystemImpl.init (SystemImpl.hx:93)
    at Function.kha_System.init (System.hx:26)
    at Function.Main.main (Main.hx:15)
    at ControllerBuilder.hx:7
kha_SystemImpl.init	@	SystemImpl.hx:93
kha_System.init	@	System.hx:26
Main.main	@	Main.hx:15
(anonymous)	@	ControllerBuilder.hx:7
`

**Comment by RobDangerous** [comment]
Krom's reason to exist from a Kha perspective is to provide functionality which is not available in a browser - so, no, that's not supposed to work. Just compile to html5 instead.

**Comment by hoseyjoe** [comment]
Thank you Rob

**Comment by hoseyjoe** [comment]
Note for others: HTML5 hxproj uses reference to electron (VSCode).  Need to remove "-D sys_debug-html5" from project or compile with hxml and remove "-D sys_debug-html5" from there. Otherwise you will get `SystemImpl.hx:59 ReferenceError: require is not defined
    at Function.kha_SystemImpl.init (SystemImpl.hx:67)
    at Function.kha_System.init (System.hx:26)
    at Function.Main.main (Main.hx:15)
    at SyncBuilder.hx:9
    at SyncBuilder.hx:9`

**Comment by hoseyjoe** [comment]
Not sure how to make Krom make release vs debug html5

**Comment by RobDangerous** [comment]
Oh, I think you're still doing it wrong, debug-html5 is not for browsers either. Use ctrl+b in Kode Studio and choose html5.
