### ISSUE TITLE
Building errors/warnings

### ISSUE THREAD

**Issue by AFWSI** [Kode/Krom#63]
Hello,

I'm having issues trying to build with Visual Studio 2017. I've tried with toolkit 141 and 140 and I get errors and warnings with both. Here's a list of 9 errors and 35 warnings, this was with toolkit 140.
[krom_errors.txt](https://github.com/Kode/Krom/files/1670516/krom_errors.txt)

**Comment by RobDangerous** [comment]
Look like you use a newer version of Kore than the one Krom currently points to.

**Comment by AFWSI** [comment]
Is it because I did this git clone git://github.com/Kode/Kore.git. I downloaded as zip and tried. I only get like 1 error and 30 something warnings now. Another thing I noticed, is in solution explorer it has a red circle that says ignored. I'm new to using Visual Studio, so I'm sure my issues are something simple.

**Comment by RobDangerous** [comment]
That one was a proper problem, even the repo pointed to a wrong version of Kore after a pull request. Give it another try now and make sure to select x64 in Visual Studio in the Win32/x64 dropdown.
