### ISSUE TITLE
Script serialization

### ISSUE THREAD

**Issue by luboslenco** [Kode/Krom#85]
Discovering more Chakra perks, there appears to be a possibility to cache the parsed `krom.js` file for faster startup in distributed Krom-powered programs. We could provide some tool to do this task and then check for the `krom.bin` file presence when Krom is launching.

- https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#script-serialization-with-lazy-source-loading
- https://github.com/Microsoft/ChakraCore/wiki/JsSerialize

**Comment by RobDangerous** [comment]
Let's add some startup parameter to Krom, something like --writebin.

**Comment by luboslenco** [comment]
Getting a crash in `JsSerialize`, leaving this snippet here to investigate later.

```cpp
void serializeScript(char* code, char* outpath) {
#ifdef KORE_WINDOWS
	AttachProcess(GetModuleHandle(nullptr));
#else
	AttachProcess(nullptr);
#endif
	JsCreateRuntime(JsRuntimeAttributeNone, nullptr, &runtime);
	JsContextRef context;
	JsCreateContext(runtime, &context);
	JsSetCurrentContext(context);

	JsValueRef codeObj, bufferObj;
	JsCreateExternalArrayBuffer((void*)code, (unsigned int)strlen(code), nullptr, nullptr, &codeObj);
	JsSerialize(codeObj, &bufferObj, JsParseScriptAttributeNone);
	Kore::u8* buffer;
	unsigned bufferLength;
	JsGetArrayBufferStorage(bufferObj, &buffer, &bufferLength);
	
	FILE* file = fopen(outpath, "wb");
	if (file == nullptr) return;
	fwrite(buffer, 1, (int)bufferLength, file);
	fclose(file);
}
```

**Comment by RobDangerous** [comment]
That function is a serial process killer.
