### ISSUE TITLE
Access to dom in krom?

### ISSUE THREAD

**Issue by hoseyjoe** [Kode/Krom#97]
We have a electron/nwjs type app that does both dom and webgl calls. Just curious if that would be possible in Krom

1. I assume the krom.exe has removed all DOM stuff and is only the webgl portion of Chakra?
2. Could it be easily re-added/made in custom compile?

**Comment by RobDangerous** [comment]
1. No, there isn't any web API in Krom, there's no DOM and no WebGL and that's the point. There isn't any WebGL in Chakra either, it's just a JavaScript interpreter.
2. No.

I don't understand your request - what you want is exactly Electron, so please just continue to use that. Also keep in mind, Krom's punchline is "We worship Krom, we banish the DOM".

**Comment by hoseyjoe** [comment]
ya, I did not understand how/what Chakra /Krom were. Makes sense. My question was in part to suss that all out. Thank you
